//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kd2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_cars
    {
        public int cars_id { get; set; }
        public int owners_id { get; set; }
        public Nullable<System.DateTime> date_of_purchase { get; set; }
        public Nullable<int> orders_id { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Owners Owners { get; set; }
    }
}
