//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kd2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicess()
        {
            this.Spare_parts_in_servics = new HashSet<Spare_parts_in_servics>();
        }
    
        public int servicess_id { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> masters_id { get; set; }
        public Nullable<int> orders_id { get; set; }
    
        public virtual Masters Masters { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Type_of_jobs Type_of_jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spare_parts_in_servics> Spare_parts_in_servics { get; set; }
    }
}
