//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kd2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spare_parts_in_servics
    {
        public int parts_id { get; set; }
        public int servicess_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual New_spare_parts New_spare_parts { get; set; }
        public virtual Servicess Servicess { get; set; }
    }
}
